# Generated by Django 4.2.6 on 2023-11-30 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logbook_signature_date', models.DateField()),
                ('internship_report_submit_date', models.DateField()),
                ('internship_report_status', models.CharField(max_length=225)),
                ('oral_exam_date', models.DateField()),
                ('oral_exam_status', models.CharField(max_length=225)),
                ('remark_notices', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.studentprofile')),
            ],
        ),
    ]
