# Generated by Django 4.2.6 on 2023-12-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0002_studentdocumentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_number',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
