# Generated by Django 4.2.6 on 2023-12-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0003_studentprofile_student_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(blank=True, max_length=225, null=True)),
                ('department', models.CharField(max_length=225)),
                ('academic_year', models.CharField(max_length=225)),
                ('eligibility_letter', models.BooleanField(default=True)),
                ('date_of_letter_approval', models.DateField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_letter_approval',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='eligibility_letter',
            field=models.BooleanField(default=True),
        ),
    ]
