# Generated by Django 4.2.6 on 2023-12-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0004_onboardstudent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardstudent',
            name='academic_year',
            field=models.CharField(choices=[('SPRING 2022-2023', 'SPRING 2022-2023'), ('SUMMMER 2022-2023', 'SUMMER 2022-2023'), ('FALL 2022-2023', 'FALL 2022-2023')], max_length=225),
        ),
        migrations.AlterField(
            model_name='studentdocumentation',
            name='internship_report_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Correction', 'Correction')], max_length=225),
        ),
    ]
