# Generated by Django 4.2.6 on 2023-12-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0005_alter_onboardstudent_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardstudent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
