# Generated by Django 4.2.6 on 2023-12-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0006_onboardstudent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardstudent',
            name='onboarding_id',
            field=models.CharField(default='8b843107-00bb-4231-8018-05af4e93540b', max_length=225),
        ),
    ]
