# Generated by Django 4.2.6 on 2023-12-14 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SummerApp', '0005_initial'),
        ('StudentApp', '0007_onboardstudent_onboarding_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardstudent',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SummerApp.department'),
        ),
        migrations.AlterField(
            model_name='onboardstudent',
            name='onboarding_id',
            field=models.CharField(default='a3a13e24-9fe8-4fec-b9bd-088c00addb21', max_length=225),
        ),
    ]
