# Generated by Django 4.2.6 on 2023-12-14 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SummerApp', '0005_initial'),
        ('StudentApp', '0008_alter_onboardstudent_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardstudent',
            name='onboarding_id',
            field=models.CharField(default='89b1e1d1-15a6-4615-a771-aeada80952a5', max_length=225),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Student_department', to='SummerApp.department'),
        ),
    ]
