# Generated by Django 4.2.6 on 2023-12-14 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0010_onboardadvisor'),
        ('StudentApp', '0009_alter_onboardstudent_onboarding_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardstudent',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserProfile.advisorprofile'),
        ),
        migrations.AlterField(
            model_name='onboardstudent',
            name='onboarding_id',
            field=models.CharField(default='977bb8e9-c65d-4727-8250-64e9c55ef920', max_length=225),
        ),
    ]
