# Generated by Django 4.2.6 on 2023-12-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0010_alter_onboardstudent_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardstudent',
            name='onboarding_id',
            field=models.CharField(default='856d515e-4fac-4491-b766-92e67d676673', max_length=225),
        ),
    ]
