# Generated by Django 4.2.6 on 2023-12-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0011_alter_onboardstudent_onboarding_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='department',
        ),
        migrations.AlterField(
            model_name='onboardstudent',
            name='onboarding_id',
            field=models.CharField(default='a2d0d32c-6dc8-4f51-9553-95f2bad05626', max_length=225),
        ),
    ]
