# Generated by Django 4.2.6 on 2023-12-14 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SummerApp', '0005_initial'),
        ('StudentApp', '0014_alter_onboardstudent_onboarding_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Student_department', to='SummerApp.department'),
        ),
        migrations.AlterField(
            model_name='onboardstudent',
            name='onboarding_id',
            field=models.CharField(default='dbe4ddbc-497c-43b2-91e7-e6287f3d2d60', max_length=225),
        ),
    ]
