# Generated by Django 4.2.6 on 2023-12-14 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0010_onboardadvisor'),
        ('StudentApp', '0015_studentprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardstudent',
            name='onboarding_id',
            field=models.CharField(default='4a17a3f7-6caa-4c5b-af73-e7842f6837e8', max_length=225),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appreoved_by_who', to='UserProfile.advisorprofile'),
        ),
    ]
