# Generated by Django 4.2.6 on 2023-12-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0016_alter_onboardstudent_onboarding_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardstudent',
            name='onboarding_id',
            field=models.CharField(default='156e9928-0340-475f-9811-e6fb98aa5921', max_length=225),
        ),
    ]
