# Generated by Django 4.2.6 on 2023-12-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0020_alter_onboardstudent_onboarding_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardstudent',
            name='onboarding_id',
            field=models.CharField(default='fb370bf4-767b-4b27-81fc-09357ca50d05', max_length=225),
        ),
    ]
