# Generated by Django 4.2.6 on 2023-10-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_rename_profile_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='approved_by',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='date_of_letter_approval',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='eligibility_letter',
            field=models.BooleanField(default=False),
        ),
    ]
