# Generated by Django 4.2.6 on 2023-10-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0004_studentprofile_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_letter_approval',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
