# Generated by Django 4.2.6 on 2023-11-30 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0005_alter_studentprofile_date_of_letter_approval'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
