# Generated by Django 4.2.6 on 2023-12-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SummerApp', '0004_delete_department'),
        ('UserProfile', '0007_remove_advisorprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvisorProfile',
        ),
    ]
