# Generated by Django 4.2.6 on 2023-10-31 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_advisorprofile'),
        ('SummerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.advisorprofile'),
        ),
    ]
