# Generated by Django 4.2.6 on 2023-10-31 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0004_studentprofile_approved_by_and_more'),
        ('SummerApp', '0002_alter_department_advisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserProfile.advisorprofile'),
        ),
    ]
