# Generated by Django 4.2.6 on 2023-12-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SummerApp', '0003_alter_department_advisor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
