# Generated by Django 4.2.6 on 2023-12-18 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0010_onboardadvisor'),
        ('SummerApp', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UserProfile.advisorprofile'),
        ),
    ]
