# Generated by Django 4.2.6 on 2023-12-07 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StudentApp', '0003_studentprofile_student_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=225)),
                ('country', models.CharField(max_length=225)),
                ('application_status', models.BooleanField(default=False)),
                ('is_selected', models.BooleanField(default=False)),
                ('remark', models.TextField()),
                ('company_information_file', models.FileField(upload_to='', verbose_name='company-information/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.studentprofile')),
            ],
        ),
    ]
