# Generated by Django 4.2.6 on 2023-12-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApplication', '0003_application_date_of_applications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='date_of_applications',
            new_name='date_of_application',
        ),
    ]
