# Generated by Django 4.2.6 on 2023-12-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApplication', '0004_rename_date_of_applications_application_date_of_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='company_information_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='company-information/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
